//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raklet.Models.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLUTION
    {
        public int SOLUTION_ID { get; set; }
        public string NAME_SURENAME { get; set; }
        public string E_MAIL { get; set; }
        public string SOLUTION1 { get; set; }
        public Nullable<int> SUBID { get; set; }
    
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
